myproject/myapp/urls.py
from django.conf.urls import url, include
from .views import index, tambahstatus, profil

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'tambahstatus', tambahstatus, name='tambahstatus'),
    url(r'^profil', profil, name = 'profil'),
]

myproject/myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('myapp.urls', 'myapp'), namespace='myapp')),
]

myproject/myapp/models.py
from django.db import models

# Create your models here.
class status(models.Model):
	deskripsi = models.TextField(max_length=300)
	tanggal = models.DateTimeField(auto_now_add=True)

myproject/myapp/forms.py
from django import forms

class status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    deskripsi_attrs = {
        'type': 'text',
        'placeholder':'Apa yang anda pikirkan...'
    }

    deskripsi = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=deskripsi_attrs))

myproject/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import status
from .forms import status_Form

# Create your views here.
response={}
def index(request):
    response['stats'] = status_Form
    response['status'] = status.objects.all()
    html = 'index.html'
    return render(request, html, response)


def tambahstatus(request):
    form = status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['deskripsi'] = request.POST['deskripsi']
        a = status(deskripsi=response['deskripsi'])
        a.save()
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')
		
def profil(request):
	return render(request, 'profil.html')

myproject/myapp/templates/index.html
<!DOCTYPE html>
<html>
<head>
<title>Story6_GracielaChikaPutri</title>
</head>
<body style="background-color:AliceBlue;">
<h1 class="main-title">Hello, Apa kabar?</h1>
<hr/>

<div class="container">
    <a href="profil.html">
        <button>Profil</button>
    </a>
    <form id="form" method="POST" action="{% url 'myapp:tambahstatus' %}">
        <h2>Masukkan status</h2>
        {% csrf_token %}
        {{ stats }}
        <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
        <br>
    </form>
</div>


<div style="margin: 5% 5%">
    <h2>My Status</h2>
    <div style = "width: 80%">
        <table class="table" border="#0000" style="width: 100%">
            <tr background-color="#ffff">
            <th style="width: 40%">Status</th>
            <th style="width: 60%">Tanggal</th>
           </tr>
           {%for e in status%}
           <tr background-color=#ffff>
            <td>{{e.deskripsi}}</td>
            <td>{{e.tanggal}}</td>
           </tr>
           {%endfor%}
        </table>
    </div>
</div>

</body>

</html>

myproject/myapp/templates/profil.html
<!DOCTYPE html>
<html>
<head>
<title>Chika Putri</title>
</head>
<body style="background-color:AliceBlue;">

<h1 style="text-align:center;">Profil</h1>

<br><img src="https://scontent.fcgk12-1.fna.fbcdn.net/v/t1.0-9/33147992_1508943735899972_6159831298375417856_n.jpg?_nc_cat=110&_nc_eui2=AeFFsbDIImIUM1YqrKIBXvDFn27KStXl-Z2j13WVaU4XeyROP5A2sJxfU6y0GpjS5WtUf14dRdCbcZmgCqo4VKUgvYmn1IDM3RQE28ZeaqmItQ&oh=2c5907ac39548f3da844c1b6e594c39e&oe=5C315A9A" alt="Meeehh" class="center" style="border-radius: 10%"> <br>
<p style="text-align:center;">	Nama: Graciela Chika Putri<br>
	NPM : 1706103436 <br>
	Tempat kuliah : UI <br>
	Hobi : Menyanyi </p> <br>
		
</body>
<style>
.center {
		display: block;
		margin-left: auto;
		margin-right: auto;
		width: 20%;
		height: 20%;
		}
</style>
</html>